### GET / 
GET http://localhost:5003

### Register a user POST /AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "gargamel@gmail.com",
    "password": "123321"
}
###

### Login a user POST /AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "gargamel@gmail.com",
    "password": "123321"
}
###

### Fetch all todos GET /TODOS (protected)
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3ODQxODQxLCJleHAiOjE3Mzc5MjgyNDF9.RHYheJlK0AZ2P79_F9QSFeos_mkukCyyzQF-0K6lCdA
###

### Creates a new todo POST /TODOS (protected)
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3ODQxODQxLCJleHAiOjE3Mzc5MjgyNDF9.RHYheJlK0AZ2P79_F9QSFeos_mkukCyyzQF-0K6lCdA
Content-Type: application/json

{
    "task": "Finish coding the projects"
}
###

### Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:5003/todos/2?page=4"
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3ODQxODQxLCJleHAiOjE3Mzc5MjgyNDF9.RHYheJlK0AZ2P79_F9QSFeos_mkukCyyzQF-0K6lCdA
Content-Type: application/json

{
    "completed": 1
}
###

### Delete a todo DELETE /TODOS/:ID (protected)
DELETE http://localhost:5003/todos/2"
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3ODQxODQxLCJleHAiOjE3Mzc5MjgyNDF9.RHYheJlK0AZ2P79_F9QSFeos_mkukCyyzQF-0K6lCdA
###
